### ISSUE TITLE
Google Analytics support

### ISSUE THREAD

**Issue by ofadam** [jks-prv/Beagle_SDR_GPS#247]
Would there be an easy way to add Google Analytics support to the radio via an admin page field? This would help those with public radios track where people are visiting from.

**Comment by jks-prv** [comment]
Already there. Scroll to the bottom of the webpage tab on the admin page.

**Comment by ofadam** [comment]
Sure enough! I'm not sure how I missed it.

**Comment by jks-prv** [comment]
Well, the admin page is complicated enough now that it's easy to miss things.

Note that when editing the text box it is saved to the Kiwi configuration only after each return/enter keypress. This behavior is due to the same code being used as for single-line field processing. I need to fix this so live editing causes a save after a short timeout.
