### ISSUE TITLE
status field in admin webpage doesn't show in running display 

### ISSUE THREAD

**Issue by K6TD** [jks-prv/Beagle_SDR_GPS#318]
After filling in the status field of the admin webpage tab, could not find the status information displayed on the running web page.  Rebooted the beagle.

Updating the owner information did show up on the running web page.

KiwiSDR v 1.336. browser is Safari 13.0.1.  Also tried on chrome 78.0.3904.87

kiwisdr.k6mtu.net

**Comment by jks-prv** [comment]
Changing these fields on your Kiwi worked fine for me.

A couple of issues could be at play. When the device you are running the browser on has a narrow display fields are deleted from the top bar of the running page (so that everything remaining fits the width of the display). The first to be removed is the "owner info". So perhaps that is why you are not seeing it.

The "status" field takes a little time before it appears on the top line of the stats tab of the control panel when you first load the running page.

In both cases after you make a change on the admin page you must reload the running page before the changes will be seen.
