### ISSUE TITLE
External users and internal users on the KiwiSDR

### ISSUE THREAD

**Issue by zanco** [jks-prv/Beagle_SDR_GPS#36]
Hi. IF I connect to my own KiwiSDR within my local network that receiver only shows my connection. If I connect by the external IP address (or dyndns redirector) those connections do not show up.

I am not shure if that is a problem, but I could connect 3 browsers locally to my KiwiSDR and still had 2 external connections, making a total of 5 reveicers 

Thanks,
Ben

**Comment by jks-prv** [comment]
When you say "do not show up" you mean the external connections don't result in entries in the status panel at the lower left of a local connection? (or on the status tab of a connection to the admin page?) It takes a few moments after a connection actually occurs before the entry shows up in the status. And it also takes one full minute for the entry to be removed, and the connection slot can be reused, after the connection has been closed. This is because of how the "keep-alive" logic works.

There are really only 4 channels. It is impossible for there to be more than 4 receiver connections. However you can have multiple admin connections open simultaneously.

**Comment by jks-prv** [comment]
Hi Ben,

When you say "do not show up" you mean the external connections don't result in entries in the status panel at the lower left of a local connection? (or on the status tab of a connection to the admin page?) It takes a few moments after a connection actually occurs before the entry shows up in the status. And it also takes one full minute for the entry to be removed after the connection has been closed. This is because of how the "keep-alive" logic works.

There are really only 4 channels. It is impossible for there to be more than 4 receiver connections. However you can have multiple admin connections open simultaneously.

Best regards,
John, ZL/KF6VO

**Comment by zanco** [comment]
Hi John,
If I run one instance from the local IP address (192.168.0.46:8073 ) and one from pe2bz.dyndns.org:8073 the status panel on the local IP address only shows my personal connection, but the pe2bz.dyndns.org also shows the external connenctions. It looks like the local connection and the external internet connection do not know of each other.

Does that make it more clear, or more complicated ?
I will try to add screenshots this weekend.

Kind regards,
Ben

**Comment by jks-prv** [comment]
Okay, so you're saying that the status panel shown from a browser connected from the local network (192.168.0.46) is not showing another connection you've made from the outside (the Internet) using a mobile device or something that doesn't use your local network?

I know this works. I tried it just now with my Kiwi here and it works fine. Both connections show two connections each: the connection from the local network (ip = 192…) and the one coming from the Internet I made using my iPhone using the cell network (WiFi turned off) so the traffic is coming from the Internet. So I would really like to understand what you are seeing exactly. Thank you.

**Comment by icm7216** [comment]
Hi,
using an ad-blocking add-on?
When Adblock-Plus block the XHR request of user stats, it becomes like this

![block_kiwi](https://cloud.githubusercontent.com/assets/16305594/19707171/0fd06144-9b51-11e6-8fbf-b271da7faff0.png)

Please try, if you use that like an Adblock-Plus.
Change setting to accept your KiwiSDR URL into  an Adblock-Plus.
When Adblock-Plus accept the XHR request of user stats, it becomes like this
![accept_kiwi](https://cloud.githubusercontent.com/assets/16305594/19707177/15903a6e-9b51-11e6-807a-ec39dcda61a5.png)

**Comment by jks-prv** [comment]
Wow, that's interesting. I run ABP on Safari and FF and I never see this. Does this happen with default ABP settings?

**Comment by icm7216** [comment]
There is no default. I added 3rd party filter-list of "ABP Japanese Paranoid filters". It's famous in japanese.
See: [k2jp/abp-japanese-filters](https://github.com/k2jp/abp-japanese-filters)

In this case, `^stats^` key word is hit in XHR request message.
```
http://kiwisdr.com:8073/USR?stats=1&config=1&update=1&ch=0
```

**Comment by jks-prv** [comment]
Okay, so I looked at the ABP filter rule page for a few minutes. Looks like I just have to not use generic keywords in the XHRs. I'll change that. Any better suggestions for me?

**Comment by icm7216** [comment]
hmm... 
how about "st"? This is a part of the word of "status". 
I think that short enough word is not registered with an ABP block list. because it causes other troubles when it matches most words.

See: [filter-cheatsheet - ABP](https://adblockplus.org/filter-cheatsheet)

**Comment by icm7216** [comment]
I don't have much confidence that ...
Though ABP block list format seems to be different from the match of the regular expression, also, it will be matched if `^st^` key word has registered with an ABP block list. so difficult.

**Comment by mmagin** [comment]
In my humble opinion, modifying the keys in the query string from easily readable words to obscure things only to make this ad blocking list happy is pretty unreasonable.  Notably at the top that list says:                                                               

"Title: ABP Japanese Paranoid filters (ONLY FOR Japanese and experienced users: READ Support Policy)"                                                      

Which to me suggests that it's very likely to cause unnecessary false positives.

**Comment by mmagin** [comment]
In my humble opinion, modifying the keys in the query string
from easily readable words to obscure things only to make this
ad blocking list happy is pretty unreasonable.  Notably at the
top that list says:

"Title: ABP Japanese Paranoid filters (ONLY FOR Japanese and experienced
users: READ Support Policy)"

Which to me suggests that it's very likely to cause unnecessary
false positives.

**Comment by jks-prv** [comment]
OTOH, anything I can do to prevent another support email is a win in my opinion. I'm up to two hours each morning answering emails, and we've hardly gotten started, lol.

Maybe this is how mankind will finally end. Not in World War 3, but in a gigantic DDoS / SPAM / ABP / Social Media / … meltdown, ha ha.

**Comment by icm7216** [comment]
Sure, My case is only one example. so, it is not necessary to be concerned with a specific block-list.
The important point is the keyword, that should not be blocked for most other Kiwi users XHR messages.

We have to wait for Ben's screenshots.
