### ISSUE TITLE
Admin Login Screen Rejecting Passwords the Admin Password Screen Accepted!

### ISSUE THREAD

**Issue by Tenacious-Techhunter** [jks-prv/Beagle_SDR_GPS#66]
We entered an XKCD-style Admin password just shy of 40 characters; all lower case letters, 3 spaces, and a dash. The json file appears to have correctly stored the password (all letters present and correct, spaces converted to "%20", the dash unconverted and as a dash character).

But the login field refuses to accept the password.

Please use the same password acceptance criteria and mechanism in both fields so accepted passwords are not rejected.

**Comment by jks-prv** [comment]
Yes, embedded white space in passwords is not handled correctly (although this bug is not yet listed in the master bug list).
We are in the middle of a huge security improvement effort. This will include fixing a lot of these problems, getting rid of the static fixed-sized buffers, misuses of strcpy() et. al. All the shortcuts we took to get the prototype out expediently are coming back to bite us.
